User.create!(name: "酒井", age: 22)
User.create!(name: "斎藤", age: 25)
User.create!(name: "山", age: 31)
User.create!(name: "山田", age: 32)
User.create!(name: "池辺", age: 33)
User.create!(name: "溝上", age: 35)
